name: Create Release for ToolTipWP Plugin

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Create temporary directory for packaging
      - name: Create temporary directory
        run: mkdir temp_dir

      # Copy specified files to the temporary directory
      - name: Copy necessary files to the temporary directory
        run: |
          cp tooltipwp.php temp_dir/
          cp github-update.php temp_dir/
          cp -r app temp_dir/app
          cp -r build temp_dir/build

      # Rename directory to the desired folder name
      - name: Rename directory
        run: mv temp_dir tooltipwp

      # Zip the packaged files
      - name: Create zip archive
        run: |
          zip -r tooltipwp-${{ github.event.inputs.tag }}.zip tooltipwp

      # Create a new GitHub release with the packaged zip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: tooltipwp-${{ github.event.inputs.tag }}.zip
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
